x-back-env: &back-env
  environment:
  - APP_ENV=local
  - APP_DEBUG=true
  - APP_URL=http://localhost:8000
  - FRONTEND_URL=http://localhost:8080
  - KAVENEGAR_TOKEN=
  - KAVENEGAR_SENDER_NUMBER=
  - TELEGRAM_BOT_TOKEN=
#  Change the secret
  - JWT_SECRET=mysecret

x-front-env: &front-env
  environment:
#   Change the secret (at least 32 characters)
    - NEXTAUTH_SECRET=GK/IKHJ55WUBSIDAFLT3vcQmud1t5PIZHsclw40JtVs=
    - NEXTAUTH_URL=http://localhost:8000
    - BASE_URL=http://nginx:80/api/v1/


services:
    skylogs-back:
        build: apps/backend
        container_name: skylogs_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - app_data:/var/www/html
        networks:
            - skylogs_net
        depends_on:
            - mongo
            - redis
        <<: *back-env

    nginx:
        image: nginx:latest
        container_name: skylogs_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - app_data:/var/www/html
            - ./apps/backend/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - skylogs_net
        depends_on:
            - skylogs-back

    mongo:
        image: mongo:latest
        container_name: skylogs_mongo
        restart: unless-stopped
        ports:
            - "27018:27017"
        networks:
            - skylogs_net
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:latest
        container_name: skylogs_redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        networks:
            - skylogs_net

    horizon:
        build:
            context: apps/backend
            dockerfile: HorizonDockerfile
        container_name: skylogs_horizon
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - app_data:/var/www/html
        depends_on:
            - skylogs-back
            - mongo
            - redis
        networks:
            - skylogs_net
        <<: *back-env


    front:
        build: apps/frontend
        restart: unless-stopped
        ports:
            - 8080:3000
        networks:
            - skylogs_net
        depends_on:
            - nginx
        <<: *front-env

    skylogs-sentinel:
        build: skylogs-sentinel
        container_name: skylogs-sentinel
        restart: always
        depends_on:
        - skylogs-back
        environment:
          - SENTINEL_ID=dc2-sentinel
          - SENTINEL_ROLE=secondary
          - MAIN_SKYLOGS_HEARTBEAT_URL=http://skylogs-core:8080/heartbeat
          - HEARTBEAT_INTERVAL=5s
          - HEARTBEAT_TIMEOUT=3s
          - FAIL_THRESHOLD=3
          - ALERT_WEBHOOK_URL=http://skylogs-core:8080/internal/alerts/sentinel
        volumes:
          - ./apps/sentinel/config.yaml:/app/config.yaml:ro
        ports:
          - "9191:9191"
        networks:
          - skylogs_net
networks:
    skylogs_net:
        driver: bridge

volumes:
    app_data:
    mongo_data:
        driver: local
